apiVersion: ray.io/v1
kind: RayService
metadata:
  name: simple-locust
spec:
  upgradeStrategy:
    type: NewClusterWithIncrementalUpgrade
    clusterUpgradeOptions:
      gatewayClassName: istio
      stepSizePercent: 10
      intervalSeconds: 30
      maxSurgePercent: 20
  serveConfigV2: |
    applications:
      - name: simple_app
        import_path: locust_test/simple_serve.app
        route_prefix: /test
        runtime_env:
          working_dir: "https://github.com/ray-project/serve_config_examples/archive/refs/heads/master.zip"
        deployments:
          - name: SimpleDeployment
            autoscaling_config:
              min_replicas: 1
              max_replicas: 3
              target_ongoing_requests: 2
              max_ongoing_requests: 6
              upscale_delay_s: 0.5
            ray_actor_options:
              num_cpus: 2
  rayClusterConfig:
    rayVersion: "2.49.2"
    enableInTreeAutoscaling: true
    headGroupSpec:
      rayStartParams:
        num-cpus: "0"
      template:
        spec:
          containers:
            - name: ray-head
              image: rayproject/ray:2.49.2
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve
    workerGroupSpecs:
      - groupName: small-group
        replicas: 1
        minReplicas: 1
        maxReplicas: 4
        template:
          spec:
            containers:
              - name: ray-worker
                image: rayproject/ray:2.49.2
                lifecycle:
                  preStop:
                    exec:
                      command: ["/bin/sh", "-c", "ray stop"]
                resources:
                  requests:
                    cpu: "2"
                    memory: "1Gi"
